name: TESTS

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    tests:
        name: TESTS
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [24.x]

        steps:
            - uses: actions/checkout@v7

            - uses: pnpm/action-setup@v6

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint

            - name: Format Check
              run: pnpm format:check

            - name: Build
              run: pnpm build

            - name: Test Unit
              run: pnpm test

            - name: Test e2e
              run: pnpm test:e2e
